### ISSUE TITLE
Vela Addon configuration file for enabling multiple addons

### ISSUE THREAD

**Issue by glaxman** [kubevela/community#143]
We have some questions about installing addons using the KubeVela CLI. The current approach (vela addon enable <addon-name> <addon-parameters>) is good for enabling a single addon, but we’d like to enable multiple addons from the CLI using a single command. Specifically, we’d like to:
Enable a list of addons
For each addon, optionally set the version, parameters, clusters, etc.
Reference this configuration from a file, so we can version it (similar to a k8s manifest)
And we want the vela CLI to read this configuration file and execute the vela addon enable command for each addon.
Example config:
- name: jspolicy
  version: 0.1.1
  values:
    replicas: 1
    jspolicy.resources.requests.memory: "128Mi"
    jspolicy.resources.requests.cpu: "50m"
    jspolicy.resources.limits.memory: "1024Mi"
    jspolicy.resources.limits.cpu: "1000m"
- name: external-secrets
  version: 0.1.2
  values:
    replicas: 3
    resources.requests.memory: "100Mi"
    resources.requests.cpu: "20m"
    resources.limits.memory: "200Mi"
    resources.limits.cpu: "40m"
Example command: vela addon enable --file config.yaml
This seems like a common use case for most users. We want to bring this to your notice and see if this is a good requirement for the vela addon CLI. We would like to hear your thoughts on this use case.

**Comment by wonderflow** [comment]
As we discussed in the most recent community call, I don't like a new format of configuration file, it will add cognitive to our end users. There're generally two ideas after discussed with @Somefive :

### Idea 1

We can support this feature in the addon metadata like this:

```
name: my-group-addon
version: v1.0.1
description: this is a bunch of addon that can be installed for a specific scenario.
icon: https://static.kubevela.net/images/logos/KubeVela%20-03.png
url: https://kubevela.io

tags:
  - Addon-Group

bunches:
- name: jspolicy
  version: 0.1.1
  values:
    replicas: 1
    jspolicy.resources.requests.memory: "128Mi"
    jspolicy.resources.requests.cpu: "50m"
    jspolicy.resources.limits.memory: "1024Mi"
    jspolicy.resources.limits.cpu: "1000m"
- name: external-secrets
  version: 0.1.2
  values:
    replicas: 3
    resources.requests.memory: "100Mi"
    resources.requests.cpu: "20m"
    resources.limits.memory: "200Mi"
    resources.limits.cpu: "40m"

system:
  vela: ">=v1.9.0"
```

Then this group itself can be a special kind of addon that can leverage the same mechanism for share, discovery and install.

We can also support enable addon with specified metatdata in the clientside:

```
vela addon enable --file metadata.yaml
```

In this command we don't need to specify a name.


### Idea 2

In the long term, we're going to support the CLI extension. We should allow user defined CLI commands through CUE or something else that we can also support the extension market/registry to share. Then any special commands can be achieved in this case.
