### ISSUE TITLE
Addon dependencies version range

### ISSUE THREAD

**Issue by merusso** [kubevela/community#146]
As a KubeVela addon developer, when defining dependencies for an addon in metadata.yaml, I would like to set a version range for these dependencies, so that my addon will be restricted from being enabled in a cluster where the dependency version doesn't match the specified range.

I see in the [docs](https://kubevela.io/docs/platform-engineers/addon/intro) that there is a dependencies[].version property, but KubeVela doesn't seem to use this value to enforce any version requirements. Ideally this property would work similarly to the existing `system` property.

For example, in "metadata.yaml":
```yaml
name: jspolicy
version: 0.1.0
description: jsPolicy addon for KubeVela.
url: https://www.jspolicy.com/

dependencies:
  - name: fluxcd
    version: ">= 2.3.3, < 3.0.0"
  - name: foo
    version: ">= 0.1.0, < 1.0.0"

system:
  vela: ">= v1.7.0"
  kubernetes: ">= 1.24.0"
```
